### ISSUE TITLE
Less bad null handing 

### ISSUE THREAD

**Issue by schreiaj** [schreiaj/tba-at-a-glance#1]
maybe for the ones with A? P? just have it put in N/A for the ones not available at all, and maybe sf, qf, f for the ones that have match results but not alliance data

**Comment by dirtbikerxz** [comment]
and also put NP for the events that a team was not picked, instead of just A? P?

**Comment by schreiaj** [comment]
If `playoff` exists but `alliance` doesnt indicates played in elims but we don't know where.

**Comment by dirtbikerxz** [comment]
to summarize:
if playoff and alliance exists: indicate alliance and pick number
if playoff exists but alliance doesn't exist: Just put in letter of max elim leve. (Ex. qf, sf, f, w)
if playoff doesn't exist, it either means the team was not picked, or event is pre 2005ish. Solution: Restrict years to post 2004 or 2005ish, and from there on out all events with null playoffs should get a NP (not picked)

**Comment by schreiaj** [comment]
After talking to Karthik - he envisioned a dual grid one showing pick position and another showing results. I'm torn on this one. On one hand it definitely opens up the options for representing data. On the other it increases height of the overall visualization.

**Comment by dirtbikerxz** [comment]
I don't see any point of having a dual grid. Simply have a legend in the corner that says green = win, blue = finalist, yellow = semi finalist, and orange = quarter finalist. And within each cell just show what alliance they were on if the data is available, or where they got eliminated. Having two separate rows to show that data is unnecessary and a waste of valuable space. I think really smart people building really fancy robots can figure out how to read a legend.

**Comment by schreiaj** [comment]
Stuck with single grid. Cleaned up to support proper handling, now displays "Not Picked" for not picks, and "Played" when we lack Alliance data.
